### PR TITLE
Animations

### PR DESCRIPTION
**Pull request by mowolf**

### CODE REVIEW

**Comment by fellnerse** [comment]
funktioniert noch nicht ganz oder?

**Comment by mowolf** [comment]
Ne, müssen wir noch fertig machen

**Comment by mowolf** [comment]
klappt nun!

**Review by fellnerse — DISMISSED** [review]

**Comment by fellnerse** [comment]
first time the loading animation was not loaded form the server -> not showing; but after that it was laoded...so maybe we need to preload this?

**Comment by fellnerse** [comment]
[] Content of page should fade in as well
[] Coloe of footer should fade in as well

**Review by fellnerse — APPROVED** [review]
maybe also animations for content and footer

**Review by fellnerse — APPROVED** [review]

**Pull request merged**
